# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JSON
version:      1.13
version_from: lib/JSON.pm
installdirs:  site
requires:
    HTTP::Request:                 0
    HTTP::Response:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
